"""
Multi-language Model Catalog for Local AI Server (AAVA-127)

This catalog contains all available STT (Vosk, Sherpa, Kroko) and TTS (Piper, Kokoro) 
models organized by language and region.
"""

# ============== STT Models (Speech-to-Text) ==============

VOSK_STT_MODELS = [
    # === Popular / Global ===
    {"id": "vosk_en_us", "name": "English (US)", "language": "en-US", "region": "global", "backend": "vosk",
     "size_mb": 1800, "size_display": "1.8 GB", "model_path": "vosk-model-en-us-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip",
     "recommended": True, "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_en_us_small", "name": "English (US) Small", "language": "en-US", "region": "global", "backend": "vosk",
     "size_mb": 40, "size_display": "40 MB", "model_path": "vosk-model-small-en-us-0.15",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_en_in", "name": "English (India)", "language": "en-IN", "region": "asia", "backend": "vosk",
     "size_mb": 1000, "size_display": "1 GB", "model_path": "vosk-model-en-in-0.5",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-en-in-0.5.zip",
     "is_archive": True, "archive_type": "zip"},
    
    # === European Languages ===
    {"id": "vosk_fr", "name": "French", "language": "fr-FR", "region": "europe", "backend": "vosk",
     "size_mb": 1400, "size_display": "1.4 GB", "model_path": "vosk-model-fr-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-fr-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_fr_small", "name": "French Small", "language": "fr-FR", "region": "europe", "backend": "vosk",
     "size_mb": 41, "size_display": "41 MB", "model_path": "vosk-model-small-fr-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-fr-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_de", "name": "German", "language": "de-DE", "region": "europe", "backend": "vosk",
     "size_mb": 1900, "size_display": "1.9 GB", "model_path": "vosk-model-de-0.21",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-de-0.21.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_de_small", "name": "German Small", "language": "de-DE", "region": "europe", "backend": "vosk",
     "size_mb": 45, "size_display": "45 MB", "model_path": "vosk-model-small-de-0.15",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_es", "name": "Spanish", "language": "es-ES", "region": "europe", "backend": "vosk",
     "size_mb": 1500, "size_display": "1.5 GB", "model_path": "vosk-model-es-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-es-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_es_small", "name": "Spanish Small", "language": "es-ES", "region": "europe", "backend": "vosk",
     "size_mb": 39, "size_display": "39 MB", "model_path": "vosk-model-small-es-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-es-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_it", "name": "Italian", "language": "it-IT", "region": "europe", "backend": "vosk",
     "size_mb": 1200, "size_display": "1.2 GB", "model_path": "vosk-model-it-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-it-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_it_small", "name": "Italian Small", "language": "it-IT", "region": "europe", "backend": "vosk",
     "size_mb": 48, "size_display": "48 MB", "model_path": "vosk-model-small-it-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-it-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_pt", "name": "Portuguese (BR)", "language": "pt-BR", "region": "europe", "backend": "vosk",
     "size_mb": 1600, "size_display": "1.6 GB", "model_path": "vosk-model-pt-fb-v0.1.1-20220516_2113",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-pt-fb-v0.1.1-20220516_2113.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_pt_small", "name": "Portuguese Small", "language": "pt-PT", "region": "europe", "backend": "vosk",
     "size_mb": 31, "size_display": "31 MB", "model_path": "vosk-model-small-pt-0.3",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-pt-0.3.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_nl", "name": "Dutch", "language": "nl-NL", "region": "europe", "backend": "vosk",
     "size_mb": 1000, "size_display": "1 GB", "model_path": "vosk-model-nl-spraakherkenning-0.6",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-nl-spraakherkenning-0.6.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_nl_small", "name": "Dutch Small", "language": "nl-NL", "region": "europe", "backend": "vosk",
     "size_mb": 39, "size_display": "39 MB", "model_path": "vosk-model-small-nl-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-nl-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ru", "name": "Russian", "language": "ru-RU", "region": "europe", "backend": "vosk",
     "size_mb": 1800, "size_display": "1.8 GB", "model_path": "vosk-model-ru-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-ru-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ru_small", "name": "Russian Small", "language": "ru-RU", "region": "europe", "backend": "vosk",
     "size_mb": 45, "size_display": "45 MB", "model_path": "vosk-model-small-ru-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_uk", "name": "Ukrainian", "language": "uk-UA", "region": "europe", "backend": "vosk",
     "size_mb": 343, "size_display": "343 MB", "model_path": "vosk-model-uk-v3",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-uk-v3.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_pl", "name": "Polish", "language": "pl-PL", "region": "europe", "backend": "vosk",
     "size_mb": 50, "size_display": "50 MB", "model_path": "vosk-model-small-pl-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-pl-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_cs", "name": "Czech", "language": "cs-CZ", "region": "europe", "backend": "vosk",
     "size_mb": 44, "size_display": "44 MB", "model_path": "vosk-model-small-cs-0.4-rhasspy",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-cs-0.4-rhasspy.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_el", "name": "Greek", "language": "el-GR", "region": "europe", "backend": "vosk",
     "size_mb": 1100, "size_display": "1.1 GB", "model_path": "vosk-model-el-gr-0.7",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-el-gr-0.7.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_sv", "name": "Swedish", "language": "sv-SE", "region": "europe", "backend": "vosk",
     "size_mb": 289, "size_display": "289 MB", "model_path": "vosk-model-small-sv-rhasspy-0.15",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-sv-rhasspy-0.15.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_tr", "name": "Turkish", "language": "tr-TR", "region": "europe", "backend": "vosk",
     "size_mb": 35, "size_display": "35 MB", "model_path": "vosk-model-small-tr-0.3",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-tr-0.3.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ca", "name": "Catalan", "language": "ca-ES", "region": "europe", "backend": "vosk",
     "size_mb": 42, "size_display": "42 MB", "model_path": "vosk-model-small-ca-0.4",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-ca-0.4.zip",
     "is_archive": True, "archive_type": "zip"},
    
    # === Asian Languages ===
    {"id": "vosk_zh", "name": "Chinese", "language": "zh-CN", "region": "asia", "backend": "vosk",
     "size_mb": 1300, "size_display": "1.3 GB", "model_path": "vosk-model-cn-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-cn-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_zh_small", "name": "Chinese Small", "language": "zh-CN", "region": "asia", "backend": "vosk",
     "size_mb": 42, "size_display": "42 MB", "model_path": "vosk-model-small-cn-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-cn-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ja", "name": "Japanese", "language": "ja-JP", "region": "asia", "backend": "vosk",
     "size_mb": 1000, "size_display": "1 GB", "model_path": "vosk-model-ja-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-ja-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ja_small", "name": "Japanese Small", "language": "ja-JP", "region": "asia", "backend": "vosk",
     "size_mb": 48, "size_display": "48 MB", "model_path": "vosk-model-small-ja-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-ja-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ko", "name": "Korean", "language": "ko-KR", "region": "asia", "backend": "vosk",
     "size_mb": 82, "size_display": "82 MB", "model_path": "vosk-model-small-ko-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-ko-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_hi", "name": "Hindi", "language": "hi-IN", "region": "asia", "backend": "vosk",
     "size_mb": 1500, "size_display": "1.5 GB", "model_path": "vosk-model-hi-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-hi-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_hi_small", "name": "Hindi Small", "language": "hi-IN", "region": "asia", "backend": "vosk",
     "size_mb": 42, "size_display": "42 MB", "model_path": "vosk-model-small-hi-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-hi-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_vi", "name": "Vietnamese", "language": "vi-VN", "region": "asia", "backend": "vosk",
     "size_mb": 78, "size_display": "78 MB", "model_path": "vosk-model-vn-0.4",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-vn-0.4.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_tl", "name": "Filipino/Tagalog", "language": "tl-PH", "region": "asia", "backend": "vosk",
     "size_mb": 320, "size_display": "320 MB", "model_path": "vosk-model-tl-ph-generic-0.6",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-tl-ph-generic-0.6.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_gu", "name": "Gujarati", "language": "gu-IN", "region": "asia", "backend": "vosk",
     "size_mb": 136, "size_display": "136 MB", "model_path": "vosk-model-gu-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-gu-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_te", "name": "Telugu", "language": "te-IN", "region": "asia", "backend": "vosk",
     "size_mb": 33, "size_display": "33 MB", "model_path": "vosk-model-small-te-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-te-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    
    # === Middle East / Central Asia ===
    {"id": "vosk_ar", "name": "Arabic", "language": "ar", "region": "middle_east", "backend": "vosk",
     "size_mb": 1300, "size_display": "1.3 GB", "model_path": "vosk-model-ar-0.22-linto-1.1.0",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-ar-0.22-linto-1.1.0.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_fa", "name": "Farsi/Persian", "language": "fa-IR", "region": "middle_east", "backend": "vosk",
     "size_mb": 1000, "size_display": "1 GB", "model_path": "vosk-model-fa-0.5",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-fa-0.5.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_kz", "name": "Kazakh", "language": "kk-KZ", "region": "central_asia", "backend": "vosk",
     "size_mb": 378, "size_display": "378 MB", "model_path": "vosk-model-kz-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-kz-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_uz", "name": "Uzbek", "language": "uz-UZ", "region": "central_asia", "backend": "vosk",
     "size_mb": 49, "size_display": "49 MB", "model_path": "vosk-model-small-uz-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-uz-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_tg", "name": "Tajik", "language": "tg-TJ", "region": "central_asia", "backend": "vosk",
     "size_mb": 337, "size_display": "337 MB", "model_path": "vosk-model-tg-0.22",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-tg-0.22.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_ky", "name": "Kyrgyz", "language": "ky-KG", "region": "central_asia", "backend": "vosk",
     "size_mb": 190, "size_display": "190 MB", "model_path": "vosk-model-ky-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-ky-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    
    # === Other ===
    {"id": "vosk_eo", "name": "Esperanto", "language": "eo", "region": "other", "backend": "vosk",
     "size_mb": 42, "size_display": "42 MB", "model_path": "vosk-model-small-eo-0.42",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-small-eo-0.42.zip",
     "is_archive": True, "archive_type": "zip"},
    {"id": "vosk_br", "name": "Breton", "language": "br", "region": "europe", "backend": "vosk",
     "size_mb": 489, "size_display": "489 MB", "model_path": "vosk-model-br-0.8",
     "download_url": "https://alphacephei.com/vosk/models/vosk-model-br-0.8.zip",
     "is_archive": True, "archive_type": "zip"},
]

SHERPA_STT_MODELS = [
    {"id": "sherpa_en", "name": "English (Streaming)", "language": "en-US", "region": "global", "backend": "sherpa",
     "size_mb": 100, "size_display": "100 MB", "model_path": "sherpa-onnx-streaming-zipformer-en-2023-06-26",
     "download_url": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-en-2023-06-26.tar.bz2",
     "recommended": True, "is_archive": True, "archive_type": "tar.bz2"},
    {"id": "sherpa_en_offline", "name": "English (Offline Transducer)", "language": "en-US", "region": "global", "backend": "sherpa",
     "size_mb": 188, "size_display": "188 MB", "model_path": "sherpa-onnx-zipformer-en-2023-06-26",
     "download_url": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-zipformer-en-2023-06-26.tar.bz2",
     "is_archive": True, "archive_type": "tar.bz2",
     "note": "Use with SHERPA_MODEL_TYPE=offline. Validates Sherpa offline telephony without a streaming model mismatch."},
    {"id": "sherpa_en_gigaspeech_offline", "name": "English GigaSpeech (Offline Transducer)", "language": "en-US", "region": "global", "backend": "sherpa",
     "size_mb": 136, "size_display": "136 MB", "model_path": "sherpa-onnx-zipformer-gigaspeech-2023-12-12",
     "download_url": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-zipformer-gigaspeech-2023-12-12.tar.bz2",
     "is_archive": True, "archive_type": "tar.bz2",
     "note": "Fallback offline English model if sherpa-onnx-zipformer-en-2023-06-26 is unavailable."},
    {"id": "sherpa_ru_offline", "name": "Russian (Offline Transducer)", "language": "ru-RU", "region": "europe", "backend": "sherpa",
     "size_mb": 189, "size_display": "189 MB", "model_path": "sherpa-onnx-zipformer-ru-2024-09-18",
     "download_url": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-zipformer-ru-2024-09-18.tar.bz2",
     "is_archive": True, "archive_type": "tar.bz2",
     "note": "Use with SHERPA_MODEL_TYPE=offline after English offline validation passes."},
    {"id": "sherpa_zh", "name": "Chinese-English Bilingual (Streaming)", "language": "zh-CN", "region": "asia", "backend": "sherpa",
     "size_mb": 120, "size_display": "120 MB", "model_path": "sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20",
     "download_url": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20.tar.bz2",
     "is_archive": True, "archive_type": "tar.bz2"},
]

KROKO_STT_MODELS = [
    # === Kroko Embedded ONNX Models (requires INCLUDE_KROKO_EMBEDDED=true in Docker build) ===
    # Models from Banafo/Kroko-ASR repo (CC-BY-SA license, free for hobby/research/free tiers)
    {"id": "kroko_en_community_64l", "name": "Kroko English Community 64L (Embedded)", "language": "en-US", "region": "global", "backend": "kroko",
     "size_mb": 150, "size_display": "150 MB", "model_path": "Kroko-EN-Community-64-L-Streaming-001.data",
     "download_url": "https://huggingface.co/Banafo/Kroko-ASR/resolve/main/Kroko-EN-Community-64-L-Streaming-001.data",
     "recommended": True, "embedded": True,
     "note": "Requires Docker image built with INCLUDE_KROKO_EMBEDDED=true. CC-BY-SA license."},
    {"id": "kroko_nl_community_128l", "name": "Kroko Dutch Community 128L (Embedded)", "language": "nl-NL", "region": "europe", "backend": "kroko",
     "size_mb": 150, "size_display": "150 MB", "model_path": "Kroko-NL-Community-128-L-Streaming-001.data",
     "download_url": "https://huggingface.co/Banafo/Kroko-ASR/resolve/main/Kroko-NL-Community-128-L-Streaming-001.data",
     "embedded": True,
     "note": "Requires Docker image built with INCLUDE_KROKO_EMBEDDED=true. CC-BY-SA license."},
    # === Kroko Cloud API ===
    {"id": "kroko_cloud", "name": "Kroko Cloud API (12 languages)", "language": "multi", "region": "global", "backend": "kroko",
     "size_mb": 0, "size_display": "0 (Cloud)", "model_path": None,
     "download_url": None, "requires_api_key": True, "api_key_name": "KROKO_API_KEY",
     "supported_languages": ["en-US", "nl-NL", "fr-FR", "de-DE", "es-ES", "it-IT", "pt-PT", "bg-BG", "sv-SE", "tr-TR", "he-IL"]},
]

TONE_STT_MODELS = [
    {"id": "tone_ru", "name": "T-one Russian (Streaming CTC)", "language": "ru-RU", "region": "europe", "backend": "tone",
     "size_mb": 460, "size_display": "460 MB", "model_path": "t-one",
     "download_url": "https://huggingface.co/t-tech/T-one/resolve/main/model.onnx",
     "recommended": True,
     "description": "Native T-one acoustic model for Russian telephony streaming.",
     "note": "Requires INCLUDE_TONE=true in Docker build. Pair with kenlm.bin for beam_search."},
    {"id": "tone_ru_kenlm", "name": "T-one Russian KenLM", "language": "ru-RU", "region": "europe", "backend": "tone",
     "size_mb": 140, "size_display": "140 MB", "model_path": "t-one/kenlm.bin",
     "download_url": "https://huggingface.co/t-tech/T-one/resolve/main/kenlm.bin",
     "description": "Optional KenLM language model for beam search decoding.",
     "note": "Set TONE_KENLM_PATH when using TONE_DECODER_TYPE=beam_search."},
]

FASTER_WHISPER_STT_MODELS = [
    # Faster-Whisper models auto-download from HuggingFace on first use
    # Requires: docker build --build-arg INCLUDE_FASTER_WHISPER=true
    
    # === Multilingual Models ===
    {"id": "faster_whisper_tiny", "name": "Whisper Tiny (39M)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 75, "size_display": "75 MB", "model_path": "tiny",
     "download_url": None, "auto_download": True,
     "description": "Fastest, lowest accuracy. Good for quick tests.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_base", "name": "Whisper Base (74M)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 145, "size_display": "145 MB", "model_path": "base",
     "download_url": None, "auto_download": True, "recommended": True,
     "description": "Good balance of speed and accuracy for real-time.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_small", "name": "Whisper Small (244M)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 465, "size_display": "465 MB", "model_path": "small",
     "download_url": None, "auto_download": True,
     "description": "Better accuracy, still real-time on modern CPUs.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_medium", "name": "Whisper Medium (769M)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 1500, "size_display": "1.5 GB", "model_path": "medium",
     "download_url": None, "auto_download": True,
     "description": "High accuracy, needs GPU for real-time.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_large_v3", "name": "Whisper Large v3 (1.5B)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 3000, "size_display": "3 GB", "model_path": "large-v3",
     "download_url": None, "auto_download": True,
     "description": "Best accuracy, requires GPU for acceptable speed.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_large_v3_turbo", "name": "Whisper Large v3 Turbo (809M)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 1600, "size_display": "1.6 GB", "model_path": "large-v3-turbo",
     "download_url": None, "auto_download": True,
     "description": "Pruned large-v3, best speed/quality ratio. Recommended for GPU.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_distil_large_v3", "name": "Distil-Whisper Large v3 (756M)", "language": "multi", "region": "global", "backend": "faster_whisper",
     "size_mb": 1500, "size_display": "1.5 GB", "model_path": "distil-large-v3",
     "download_url": None, "auto_download": True,
     "description": "Within 1% WER of large-v3, 2x faster. Best for production.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    
    # === English-Only Models (slightly better for English) ===
    {"id": "faster_whisper_tiny_en", "name": "Whisper Tiny.en (39M)", "language": "en-US", "region": "global", "backend": "faster_whisper",
     "size_mb": 75, "size_display": "75 MB", "model_path": "tiny.en",
     "download_url": None, "auto_download": True,
     "description": "English-only, fastest option.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_base_en", "name": "Whisper Base.en (74M)", "language": "en-US", "region": "global", "backend": "faster_whisper",
     "size_mb": 145, "size_display": "145 MB", "model_path": "base.en",
     "download_url": None, "auto_download": True,
     "description": "English-only, good for real-time English transcription.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_small_en", "name": "Whisper Small.en (244M)", "language": "en-US", "region": "global", "backend": "faster_whisper",
     "size_mb": 465, "size_display": "465 MB", "model_path": "small.en",
     "download_url": None, "auto_download": True,
     "description": "English-only, excellent accuracy for English calls.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
    {"id": "faster_whisper_medium_en", "name": "Whisper Medium.en (769M)", "language": "en-US", "region": "global", "backend": "faster_whisper",
     "size_mb": 1500, "size_display": "1.5 GB", "model_path": "medium.en",
     "download_url": None, "auto_download": True,
     "description": "English-only, near-perfect accuracy with GPU.",
     "note": "Requires INCLUDE_FASTER_WHISPER=true in Docker build"},
]

WHISPER_CPP_STT_MODELS = [
    # Whisper.cpp (ggml) models - requires INCLUDE_WHISPER_CPP=true in Docker build
    # Download URLs from official ggml Whisper releases
    {"id": "whisper_cpp_tiny_en", "name": "Whisper.cpp Tiny.en", "language": "en-US", "region": "global", "backend": "whisper_cpp",
     "size_mb": 75, "size_display": "75 MB", "model_path": "ggml-tiny.en.bin",
     "download_url": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin",
     "description": "Fastest English-only model for CPU.",
     "note": "Requires INCLUDE_WHISPER_CPP=true in Docker build"},
    {"id": "whisper_cpp_base_en", "name": "Whisper.cpp Base.en", "language": "en-US", "region": "global", "backend": "whisper_cpp",
     "size_mb": 142, "size_display": "142 MB", "model_path": "ggml-base.en.bin",
     "download_url": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin",
     "recommended": True,
     "description": "Good balance for English on CPU.",
     "note": "Requires INCLUDE_WHISPER_CPP=true in Docker build"},
    {"id": "whisper_cpp_small_en", "name": "Whisper.cpp Small.en", "language": "en-US", "region": "global", "backend": "whisper_cpp",
     "size_mb": 466, "size_display": "466 MB", "model_path": "ggml-small.en.bin",
     "download_url": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin",
     "description": "Higher accuracy English model.",
     "note": "Requires INCLUDE_WHISPER_CPP=true in Docker build"},
    {"id": "whisper_cpp_medium_en", "name": "Whisper.cpp Medium.en", "language": "en-US", "region": "global", "backend": "whisper_cpp",
     "size_mb": 1500, "size_display": "1.5 GB", "model_path": "ggml-medium.en.bin",
     "download_url": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.en.bin",
     "description": "Near-best English accuracy.",
     "note": "Requires INCLUDE_WHISPER_CPP=true in Docker build"},
    {"id": "whisper_cpp_large_v3", "name": "Whisper.cpp Large v3", "language": "multi", "region": "global", "backend": "whisper_cpp",
     "size_mb": 3000, "size_display": "3 GB", "model_path": "ggml-large-v3.bin",
     "download_url": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
     "description": "Best multilingual accuracy, needs GPU.",
     "note": "Requires INCLUDE_WHISPER_CPP=true in Docker build"},
    {"id": "whisper_cpp_large_v3_turbo", "name": "Whisper.cpp Large v3 Turbo", "language": "multi", "region": "global", "backend": "whisper_cpp",
     "size_mb": 1600, "size_display": "1.6 GB", "model_path": "ggml-large-v3-turbo.bin",
     "download_url": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
     "description": "Faster large-v3 variant, excellent speed/quality.",
     "note": "Requires INCLUDE_WHISPER_CPP=true in Docker build"},
]

# ============== TTS Models (Text-to-Speech) ==============

PIPER_TTS_MODELS = [
    # === English (US) - Multiple voice options ===
    {"id": "piper_en_us_lessac_medium", "name": "Lessac (en-US, Male)", "language": "en-US", "region": "global", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_US-lessac-medium.onnx", "recommended": True,
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/en_US-lessac-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json"},
    {"id": "piper_en_us_lessac_high", "name": "Lessac High (en-US, Male)", "language": "en-US", "region": "global", "backend": "piper",
     "gender": "male", "quality": "high", "size_mb": 200, "size_display": "200 MB",
     "model_path": "en_US-lessac-high.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/high/en_US-lessac-high.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/high/en_US-lessac-high.onnx.json"},
    {"id": "piper_en_us_amy_medium", "name": "Amy (en-US, Female)", "language": "en-US", "region": "global", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_US-amy-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium/en_US-amy-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium/en_US-amy-medium.onnx.json"},
    {"id": "piper_en_us_ryan_medium", "name": "Ryan (en-US, Male)", "language": "en-US", "region": "global", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_US-ryan-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/medium/en_US-ryan-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json"},
    {"id": "piper_en_us_joe_medium", "name": "Joe (en-US, Male)", "language": "en-US", "region": "global", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_US-joe-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/joe/medium/en_US-joe-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/joe/medium/en_US-joe-medium.onnx.json"},
    
    # === English (GB) - Multiple voice options ===
    {"id": "piper_en_gb_alba_medium", "name": "Alba (en-GB, Female)", "language": "en-GB", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_GB-alba-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/en_GB-alba-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/en_GB-alba-medium.onnx.json"},
    {"id": "piper_en_gb_alan_medium", "name": "Alan (en-GB, Male)", "language": "en-GB", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_GB-alan-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alan/medium/en_GB-alan-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alan/medium/en_GB-alan-medium.onnx.json"},
    {"id": "piper_en_gb_jenny_dioco_medium", "name": "Jenny (en-GB, Female)", "language": "en-GB", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "en_GB-jenny_dioco-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx.json"},
    
    # === European Languages ===
    {"id": "piper_de_thorsten_medium", "name": "Thorsten (de-DE, Male)", "language": "de-DE", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "de_DE-thorsten-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx.json"},
    {"id": "piper_es_davefx_medium", "name": "Davefx (es-ES, Male)", "language": "es-ES", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "es_ES-davefx-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx.json"},
    {"id": "piper_es_mx_ald_medium", "name": "Ald (es-MX, Male)", "language": "es-MX", "region": "americas", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "es_MX-ald-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_MX/ald/medium/es_MX-ald-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/es/es_MX/ald/medium/es_MX-ald-medium.onnx.json"},
    {"id": "piper_fr_siwis_medium", "name": "Siwis (fr-FR, Female)", "language": "fr-FR", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "fr_FR-siwis-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx.json"},
    {"id": "piper_it_riccardo_x_low", "name": "Riccardo (it-IT, Male)", "language": "it-IT", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "x_low", "size_mb": 30, "size_display": "30 MB",
     "model_path": "it_IT-riccardo-x_low.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx.json"},
    {"id": "piper_pt_br_faber_medium", "name": "Faber (pt-BR, Male)", "language": "pt-BR", "region": "americas", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "pt_BR-faber-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx.json"},
    {"id": "piper_nl_mls_medium", "name": "MLS (nl-NL, Multi)", "language": "nl-NL", "region": "europe", "backend": "piper",
     "gender": "multi", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "nl_NL-mls-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls/medium/nl_NL-mls-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/nl/nl_NL/mls/medium/nl_NL-mls-medium.onnx.json"},
    {"id": "piper_ru_irina_medium", "name": "Irina (ru-RU, Female)", "language": "ru-RU", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "ru_RU-irina-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx.json"},
    {"id": "piper_uk_lada_x_low", "name": "Lada (uk-UA, Female)", "language": "uk-UA", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "x_low", "size_mb": 30, "size_display": "30 MB",
     "model_path": "uk_UA-lada-x_low.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/uk/uk_UA/lada/x_low/uk_UA-lada-x_low.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/uk/uk_UA/lada/x_low/uk_UA-lada-x_low.onnx.json"},
    {"id": "piper_pl_gosia_medium", "name": "Gosia (pl-PL, Female)", "language": "pl-PL", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "pl_PL-gosia_prosodic-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/gosia_prosodic/medium/pl_PL-gosia_prosodic-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/pl/pl_PL/gosia_prosodic/medium/pl_PL-gosia_prosodic-medium.onnx.json"},
    {"id": "piper_cs_jirka_medium", "name": "Jirka (cs-CZ, Male)", "language": "cs-CZ", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "cs_CZ-jirka-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx.json"},
    {"id": "piper_el_rapunzelina_low", "name": "Rapunzelina (el-GR, Female)", "language": "el-GR", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "low", "size_mb": 50, "size_display": "50 MB",
     "model_path": "el_GR-rapunzelina-low.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/el/el_GR/rapunzelina/low/el_GR-rapunzelina-low.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/el/el_GR/rapunzelina/low/el_GR-rapunzelina-low.onnx.json"},
    {"id": "piper_sv_nst_medium", "name": "NST (sv-SE, Female)", "language": "sv-SE", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "sv_SE-nst-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx.json"},
    {"id": "piper_tr_dfki_medium", "name": "DFKI (tr-TR, Male)", "language": "tr-TR", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "tr_TR-dfki-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx.json"},
    {"id": "piper_ca_upc_medium", "name": "UPC (ca-ES, Multi)", "language": "ca-ES", "region": "europe", "backend": "piper",
     "gender": "multi", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "ca_ES-upc_ona-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx.json"},
    {"id": "piper_da_talesyntese_medium", "name": "Talesyntese (da-DK, Female)", "language": "da-DK", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "da_DK-talesyntese-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/da/da_DK/talesyntese/medium/da_DK-talesyntese-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/da/da_DK/talesyntese/medium/da_DK-talesyntese-medium.onnx.json"},
    {"id": "piper_fi_harri_medium", "name": "Harri (fi-FI, Male)", "language": "fi-FI", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "fi_FI-harri-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx.json"},
    {"id": "piper_hu_anna_medium", "name": "Anna (hu-HU, Female)", "language": "hu-HU", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "hu_HU-anna-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/anna/medium/hu_HU-anna-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/hu/hu_HU/anna/medium/hu_HU-anna-medium.onnx.json"},
    {"id": "piper_no_talesyntese_medium", "name": "Talesyntese (no-NO, Female)", "language": "no-NO", "region": "europe", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "no_NO-talesyntese-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/no/no_NO/talesyntese/medium/no_NO-talesyntese-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/no/no_NO/talesyntese/medium/no_NO-talesyntese-medium.onnx.json"},
    {"id": "piper_sr_serbski_medium", "name": "Serbski (sr-RS, Male)", "language": "sr-RS", "region": "europe", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "sr_RS-serbski_institut-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sr/sr_RS/serbski_institut/medium/sr_RS-serbski_institut-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sr/sr_RS/serbski_institut/medium/sr_RS-serbski_institut-medium.onnx.json"},
    
    # === Asian Languages ===
    {"id": "piper_zh_huayan_medium", "name": "Huayan (zh-CN, Female)", "language": "zh-CN", "region": "asia", "backend": "piper",
     "gender": "female", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "zh_CN-huayan-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx.json"},
    {"id": "piper_vi_vivos_x_low", "name": "Vivos (vi-VN, Multi)", "language": "vi-VN", "region": "asia", "backend": "piper",
     "gender": "multi", "quality": "x_low", "size_mb": 30, "size_display": "30 MB",
     "model_path": "vi_VN-vivos-x_low.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vivos/x_low/vi_VN-vivos-x_low.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vivos/x_low/vi_VN-vivos-x_low.onnx.json"},
    {"id": "piper_ne_google_medium", "name": "Google (ne-NP, Multi)", "language": "ne-NP", "region": "asia", "backend": "piper",
     "gender": "multi", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "ne_NP-google-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ne/ne_NP/google/medium/ne_NP-google-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ne/ne_NP/google/medium/ne_NP-google-medium.onnx.json"},
    {"id": "piper_kk_iseke_x_low", "name": "Iseke (kk-KZ, Male)", "language": "kk-KZ", "region": "central_asia", "backend": "piper",
     "gender": "male", "quality": "x_low", "size_mb": 30, "size_display": "30 MB",
     "model_path": "kk_KZ-iseke-x_low.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/iseke/x_low/kk_KZ-iseke-x_low.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/kk/kk_KZ/iseke/x_low/kk_KZ-iseke-x_low.onnx.json"},
    
    # === Middle East ===
    {"id": "piper_ar_kareem_medium", "name": "Kareem (ar, Male)", "language": "ar", "region": "middle_east", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "ar_JO-kareem-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx.json"},
    
    # === Africa ===
    {"id": "piper_sw_lanfrica_medium", "name": "Lanfrica (sw-CD, Male)", "language": "sw", "region": "africa", "backend": "piper",
     "gender": "male", "quality": "medium", "size_mb": 100, "size_display": "100 MB",
     "model_path": "sw_CD-lanfrica-medium.onnx",
     "download_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sw/sw_CD/lanfrica/medium/sw_CD-lanfrica-medium.onnx",
     "config_url": "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/sw/sw_CD/lanfrica/medium/sw_CD-lanfrica-medium.onnx.json"},
]

KOKORO_TTS_MODELS = [
    {"id": "kokoro_82m", "name": "Kokoro 82M (Multi-language)", "language": "multi", "region": "global", "backend": "kokoro",
     "size_mb": 330, "size_display": "330 MB", "model_path": "kokoro",
     "download_url": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/kokoro-v1_0.pth",
     "config_url": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/config.json",
     "supported_languages": ["en-US", "en-GB", "ja-JP", "zh-CN", "es-ES", "fr-FR", "hi-IN", "it-IT", "pt-BR"],
     "voice_files": {
         # American English Female
         "af_heart": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/af_heart.pt",
         "af_bella": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/af_bella.pt",
         "af_nicole": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/af_nicole.pt",
         "af_sarah": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/af_sarah.pt",
         "af_sky": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/af_sky.pt",
         # American English Male
         "am_adam": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/am_adam.pt",
         "am_michael": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/am_michael.pt",
         # British English Female
         "bf_emma": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/bf_emma.pt",
         "bf_isabella": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/bf_isabella.pt",
         # British English Male
         "bm_george": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/bm_george.pt",
         "bm_lewis": "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/voices/bm_lewis.pt",
     }},
]

MELOTTS_MODELS = [
    # MeloTTS - lightweight CPU-optimized TTS with multiple English accents
    # Requires: docker build --build-arg INCLUDE_MELOTTS=true
    # Models auto-download on first use
    {"id": "melotts_en_us", "name": "MeloTTS American English", "language": "en-US", "region": "global", "backend": "melotts",
     "size_mb": 200, "size_display": "200 MB", "model_path": "EN-US",
     "download_url": None, "auto_download": True, "recommended": True,
     "description": "Clear American English voice, CPU-optimized",
     "note": "Requires INCLUDE_MELOTTS=true in Docker build"},
    {"id": "melotts_en_br", "name": "MeloTTS British English", "language": "en-GB", "region": "europe", "backend": "melotts",
     "size_mb": 200, "size_display": "200 MB", "model_path": "EN-BR",
     "download_url": None, "auto_download": True,
     "description": "British English accent",
     "note": "Requires INCLUDE_MELOTTS=true in Docker build"},
    {"id": "melotts_en_au", "name": "MeloTTS Australian English", "language": "en-AU", "region": "oceania", "backend": "melotts",
     "size_mb": 200, "size_display": "200 MB", "model_path": "EN-AU",
     "download_url": None, "auto_download": True,
     "description": "Australian English accent",
     "note": "Requires INCLUDE_MELOTTS=true in Docker build"},
    {"id": "melotts_en_in", "name": "MeloTTS Indian English", "language": "en-IN", "region": "asia", "backend": "melotts",
     "size_mb": 200, "size_display": "200 MB", "model_path": "EN-IN",
     "download_url": None, "auto_download": True,
     "description": "Indian English accent",
     "note": "Requires INCLUDE_MELOTTS=true in Docker build"},
    {"id": "melotts_en_default", "name": "MeloTTS Default English", "language": "en-US", "region": "global", "backend": "melotts",
     "size_mb": 200, "size_display": "200 MB", "model_path": "EN-Default",
     "download_url": None, "auto_download": True,
     "description": "Default English voice",
     "note": "Requires INCLUDE_MELOTTS=true in Docker build"},
]

# ============== Silero TTS Models ==============

SILERO_TTS_MODELS = [
    # === Russian (5 speakers in v3_1_ru) ===
    {"id": "silero_ru_xenia", "name": "Silero Xenia (ru, Female)", "language": "ru-RU", "region": "europe", "backend": "silero",
     "speaker": "xenia", "silero_model_id": "v3_1_ru",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True, "recommended": True,
     "description": "Russian female voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    {"id": "silero_ru_aidar", "name": "Silero Aidar (ru, Male)", "language": "ru-RU", "region": "europe", "backend": "silero",
     "speaker": "aidar", "silero_model_id": "v3_1_ru",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "Russian male voice",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    {"id": "silero_ru_baya", "name": "Silero Baya (ru, Female)", "language": "ru-RU", "region": "europe", "backend": "silero",
     "speaker": "baya", "silero_model_id": "v3_1_ru",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "Russian female voice",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    {"id": "silero_ru_kseniya", "name": "Silero Kseniya (ru, Female)", "language": "ru-RU", "region": "europe", "backend": "silero",
     "speaker": "kseniya", "silero_model_id": "v3_1_ru",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "Russian female voice",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    {"id": "silero_ru_eugene", "name": "Silero Eugene (ru, Male)", "language": "ru-RU", "region": "europe", "backend": "silero",
     "speaker": "eugene", "silero_model_id": "v3_1_ru",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "Russian male voice",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    # === English (v3_en — numbered speakers, showing a representative subset) ===
    {"id": "silero_en_0", "name": "Silero en_0 (en, Default)", "language": "en-US", "region": "global", "backend": "silero",
     "speaker": "en_0", "silero_model_id": "v3_en",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "English voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    # === German (v3_de — 5 named speakers) ===
    {"id": "silero_de_eva_k", "name": "Silero Eva K (de, Female)", "language": "de-DE", "region": "europe", "backend": "silero",
     "speaker": "eva_k", "silero_model_id": "v3_de",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "German female voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    {"id": "silero_de_karlsson", "name": "Silero Karlsson (de, Male)", "language": "de-DE", "region": "europe", "backend": "silero",
     "speaker": "karlsson", "silero_model_id": "v3_de",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "German male voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    {"id": "silero_de_friedrich", "name": "Silero Friedrich (de, Male)", "language": "de-DE", "region": "europe", "backend": "silero",
     "speaker": "friedrich", "silero_model_id": "v3_de",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "German male voice",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    # === Spanish (v3_es — numbered speakers) ===
    {"id": "silero_es_0", "name": "Silero es_0 (es, Default)", "language": "es-ES", "region": "europe", "backend": "silero",
     "speaker": "es_0", "silero_model_id": "v3_es",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "Spanish voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    # === French (v3_fr — numbered speakers) ===
    {"id": "silero_fr_0", "name": "Silero fr_0 (fr, Default)", "language": "fr-FR", "region": "europe", "backend": "silero",
     "speaker": "fr_0", "silero_model_id": "v3_fr",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "French voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
    # === Ukrainian (v3_ua) ===
    {"id": "silero_ua_mykyta", "name": "Silero Mykyta (uk, Male)", "language": "uk-UA", "region": "europe", "backend": "silero",
     "speaker": "mykyta", "silero_model_id": "v3_ua",
     "size_mb": 100, "size_display": "100 MB", "model_path": None,
     "download_url": None, "auto_download": True,
     "description": "Ukrainian male voice, 8kHz native telephony",
     "note": "Requires INCLUDE_SILERO=true in Docker build"},
]

# ============== LLM Models ==============

LLM_MODELS = [
    # === Lightweight Models (4-8 GB RAM) ===
    {"id": "tinyllama", "name": "TinyLlama 1.1B", "size_mb": 700, "size_display": "700 MB",
     "description": "Lightweight, for low-resource systems",
     "chat_format": "chatml",
     "download_url": "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
     "model_path": "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf", "recommended_ram_gb": 4},
    {"id": "llama32_3b", "name": "Llama-3.2-3B", "size_mb": 2000, "size_display": "2 GB",
     "description": "Balanced performance and quality",
     "chat_format": "llama-3",
     "download_url": "https://huggingface.co/lmstudio-community/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
     "model_path": "Llama-3.2-3B-Instruct-Q4_K_M.gguf", "recommended_ram_gb": 8},
    {"id": "phi3_mini", "name": "Phi-3-mini-4K", "size_mb": 2500, "size_display": "2.5 GB",
     "description": "Good quality, optimized for 4K context", "recommended": True,
     "chat_format": "chatml",
     "tool_calling": "experimental",
     "tool_calling_note": "Can follow tool-call prompts, but may emit malformed / truncated tool JSON in long conversations.",
     "download_url": "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf",
     "model_path": "phi-3-mini-4k-instruct.Q4_K_M.gguf", "recommended_ram_gb": 8},
    
    # === Mid-Range Models (8-16 GB RAM) ===
    {"id": "qwen25_3b", "name": "Qwen 2.5-3B Instruct", "size_mb": 2100, "size_display": "2.1 GB",
     "description": "Excellent instruction following, multilingual",
     "chat_format": "chatml",
     "tool_calling": "experimental",
     "tool_calling_note": "Supports tool calls via ChatML; smaller size may produce inconsistent structured output in long conversations.",
     "download_url": "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
     "model_path": "qwen2.5-3b-instruct-q4_k_m.gguf", "recommended_ram_gb": 8},
    {"id": "gemma2_2b", "name": "Gemma 2-2B Instruct", "size_mb": 1800, "size_display": "1.8 GB",
     "description": "Google's efficient on-device model",
     "chat_format": "gemma",
     "download_url": "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf",
     "model_path": "gemma-2-2b-it-Q4_K_M.gguf", "recommended_ram_gb": 6},
    {"id": "mistral_7b_instruct", "name": "Mistral-7B-Instruct v0.3", "size_mb": 4200, "size_display": "4.2 GB",
     "description": "Fast and capable, Apache licensed",
     "chat_format": "mistral-instruct",
     "download_url": "https://huggingface.co/MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3.Q4_K_M.gguf",
     "model_path": "Mistral-7B-Instruct-v0.3.Q4_K_M.gguf", "recommended_ram_gb": 12},
    {"id": "qwen25_7b", "name": "Qwen 2.5-7B Instruct", "size_mb": 4700, "size_display": "4.7 GB",
     "description": "Superior instruction following, good tool-call compliance",
     "chat_format": "chatml",
     "tool_calling": "recommended",
     "download_url": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF/resolve/main/qwen2.5-7b-instruct-q4_k_m.gguf",
     "model_path": "qwen2.5-7b-instruct-q4_k_m.gguf", "recommended_ram_gb": 12},
    
    # === High-Performance Models (16-24 GB RAM) ===
    {"id": "llama31_8b", "name": "Llama 3.1-8B Instruct", "size_mb": 4700, "size_display": "4.7 GB",
     "description": "Strong dialogue, good instruction following, solid tool-call compliance",
     "chat_format": "llama-3",
     "tool_calling": "recommended",
     "download_url": "https://huggingface.co/lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
     "model_path": "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf", "recommended_ram_gb": 16},
    {"id": "functionary_small_v32", "name": "Functionary Small v3.2 (8B)", "size_mb": 4920, "size_display": "4.9 GB",
     "description": "Tool-calling-tuned model for reliable structured tool outputs",
     "chat_format": "functionary-v2",
     "tool_calling": "recommended",
     "download_url": "https://huggingface.co/bartowski/functionary-small-v3.2-GGUF/resolve/main/functionary-small-v3.2-Q4_K_M.gguf",
     "model_path": "functionary-small-v3.2-Q4_K_M.gguf", "recommended_ram_gb": 16},
    {"id": "hermes3_llama31_8b", "name": "Hermes 3 (Llama 3.1 8B)", "size_mb": 4920, "size_display": "4.9 GB",
     "description": "Strong instruction following; tends to be more consistent with tool-call formatting than Phi-3",
     "chat_format": "chatml",
     "tool_calling": "recommended",
     "download_url": "https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-8B-GGUF/resolve/main/Hermes-3-Llama-3.1-8B.Q4_K_M.gguf",
     "model_path": "Hermes-3-Llama-3.1-8B.Q4_K_M.gguf", "recommended_ram_gb": 16},
    {"id": "mistral_nemo_12b", "name": "Mistral Nemo 12B Instruct", "size_mb": 7500, "size_display": "7.5 GB",
     "description": "Higher quality than 7-8B models; good tool-call compliance when properly prompted",
     "chat_format": "mistral-instruct",
     "tool_calling": "recommended",
     "download_url": "https://huggingface.co/Triangle104/Mistral_Nemo_Instruct_2407-GGUF/resolve/main/Mistral_Nemo_Instruct_2407-F16.gguf-Q4_K_M.gguf",
     "model_path": "Mistral_Nemo_Instruct_2407-F16.gguf-Q4_K_M.gguf", "recommended_ram_gb": 24},
    {"id": "command_r7b_2024_12", "name": "Command R7B (2024-12)", "size_mb": 5060, "size_display": "5.1 GB",
     "description": "Command-family instruct model; can work well for tool calls, but check license constraints",
     "chat_format": "chatml",
     "tool_calling": "recommended",
     "note": "License note: non-commercial in many distributions — review before production use.",
     "download_url": "https://huggingface.co/oncu/c4ai-command-r7b-12-2024-GGUF/resolve/main/c4ai-command-r7b-12-2024-q4_k_m.gguf",
     "model_path": "c4ai-command-r7b-12-2024-q4_k_m.gguf", "recommended_ram_gb": 16},
    {"id": "gemma2_9b", "name": "Gemma 2-9B Instruct", "size_mb": 5500, "size_display": "5.5 GB",
     "description": "Google's powerful on-device model",
     "chat_format": "gemma",
     "download_url": "https://huggingface.co/bartowski/gemma-2-9b-it-GGUF/resolve/main/gemma-2-9b-it-Q4_K_M.gguf",
     "model_path": "gemma-2-9b-it-Q4_K_M.gguf", "recommended_ram_gb": 16},
    {"id": "phi4_14b", "name": "Phi-4-14B", "size_mb": 8500, "size_display": "8.5 GB",
     "description": "Microsoft's latest, beats larger models on benchmarks",
     "chat_format": "chatml",
     "download_url": "https://huggingface.co/bartowski/phi-4-GGUF/resolve/main/phi-4-Q4_K_M.gguf",
     "model_path": "phi-4-Q4_K_M.gguf", "recommended_ram_gb": 16},
    {"id": "qwen25_14b", "name": "Qwen 2.5-14B Instruct", "size_mb": 8800, "size_display": "8.8 GB",
     "description": "Excellent for complex reasoning and coding",
     "chat_format": "chatml",
     "download_url": "https://huggingface.co/Qwen/Qwen2.5-14B-Instruct-GGUF/resolve/main/qwen2.5-14b-instruct-q4_k_m.gguf",
     "model_path": "qwen2.5-14b-instruct-q4_k_m.gguf", "recommended_ram_gb": 20},
    
    # === Cloud Options ===
    {"id": "openai_cloud", "name": "OpenAI Cloud (GPT-4)", "size_mb": 0, "size_display": "0 (Cloud)",
     "description": "Best quality, requires API key",
     "download_url": None, "model_path": None, "requires_api_key": True, "api_key_name": "OPENAI_API_KEY"},
    {"id": "groq_cloud", "name": "Groq Cloud (Llama 3)", "size_mb": 0, "size_display": "0 (Cloud)",
     "description": "Ultra-fast inference, requires API key",
     "download_url": None, "model_path": None, "requires_api_key": True, "api_key_name": "GROQ_API_KEY"},
]

# ============== Combined Catalog ==============

def get_full_catalog():
    """Get the complete model catalog organized by type."""
    return {
        "stt": VOSK_STT_MODELS + SHERPA_STT_MODELS + KROKO_STT_MODELS + TONE_STT_MODELS + FASTER_WHISPER_STT_MODELS + WHISPER_CPP_STT_MODELS,
        "tts": PIPER_TTS_MODELS + KOKORO_TTS_MODELS + MELOTTS_MODELS + SILERO_TTS_MODELS,
        "llm": LLM_MODELS,
    }

def get_models_by_language(language_code: str):
    """Get all models available for a specific language."""
    catalog = get_full_catalog()
    result = {"stt": [], "tts": []}
    
    for stt in catalog["stt"]:
        if stt.get("language") == language_code or stt.get("language") == "multi":
            result["stt"].append(stt)
    
    for tts in catalog["tts"]:
        if tts.get("language") == language_code or tts.get("language") == "multi":
            result["tts"].append(tts)
    
    return result

def get_available_languages():
    """Get list of all available languages with their support status."""
    catalog = get_full_catalog()
    languages = {}
    
    for stt in catalog["stt"]:
        lang = stt.get("language")
        if lang and lang != "multi":
            if lang not in languages:
                languages[lang] = {"stt": [], "tts": [], "region": stt.get("region", "other")}
            languages[lang]["stt"].append(stt["id"])
    
    for tts in catalog["tts"]:
        lang = tts.get("language")
        if lang and lang != "multi":
            if lang not in languages:
                languages[lang] = {"stt": [], "tts": [], "region": tts.get("region", "other")}
            languages[lang]["tts"].append(tts["id"])
    
    return languages

# Language display names for UI
LANGUAGE_NAMES = {
    "en-US": "English (US)",
    "en-GB": "English (UK)",
    "en-IN": "English (India)",
    "fr-FR": "French",
    "de-DE": "German",
    "es-ES": "Spanish (Spain)",
    "es-MX": "Spanish (Mexico)",
    "it-IT": "Italian",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese",
    "nl-NL": "Dutch",
    "ru-RU": "Russian",
    "uk-UA": "Ukrainian",
    "pl-PL": "Polish",
    "cs-CZ": "Czech",
    "el-GR": "Greek",
    "sv-SE": "Swedish",
    "tr-TR": "Turkish",
    "ca-ES": "Catalan",
    "da-DK": "Danish",
    "fi-FI": "Finnish",
    "hu-HU": "Hungarian",
    "no-NO": "Norwegian",
    "sr-RS": "Serbian",
    "zh-CN": "Chinese (Mandarin)",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "hi-IN": "Hindi",
    "vi-VN": "Vietnamese",
    "tl-PH": "Filipino/Tagalog",
    "gu-IN": "Gujarati",
    "te-IN": "Telugu",
    "ne-NP": "Nepali",
    "ar": "Arabic",
    "fa-IR": "Farsi/Persian",
    "kk-KZ": "Kazakh",
    "uz-UZ": "Uzbek",
    "tg-TJ": "Tajik",
    "ky-KG": "Kyrgyz",
    "sw": "Swahili",
    "eo": "Esperanto",
    "br": "Breton",
}

REGION_NAMES = {
    "global": "Global",
    "europe": "Europe",
    "asia": "Asia",
    "americas": "Americas",
    "middle_east": "Middle East",
    "central_asia": "Central Asia",
    "africa": "Africa",
    "other": "Other",
}
